# Generated by Django 3.1.4 on 2023-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20230409_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Unassigned'), ('2', 'Contacted'), ('3', 'Converted'), ('4', 'Unconverted')], default='1', max_length=30),
        ),
    ]
